Issue #299: unclear error message in case of multiline string argument
graph-gophers/graphql-go pull request #412
Opened 2020-10-06 19:43 UTC by suntoucha

Fix #299 

Package text/scanner, which is used to parse queries, already detects multiline strings as an error. But it only puts log message to console, as it was pointed in the issue description. Scanner can also call a function each time it encounters error 

So the idea of the fix is:
- provide Scanner a function to catch errors
- generate high-level errors in that function
- couple of tests

2020-10-06 20:28 UTC, suntoucha commented
Excuse me, can anyone give a hint what could be the difference between local test run and semaphoreci?

Local run passes ok:

> --- PASS: TestMultilineString (0.00s)
>     --- PASS: TestMultilineString/Oneline_strings_are_okay (0.00s)
>     --- PASS: TestMultilineString/Multiline_strings_are_not_allowed (0.00s)

Semaphoreci failes (part of the returned error string after "See near..." is missing):

> --- FAIL: TestMultilineString (0.00s)
>     --- PASS: TestMultilineString/Oneline_strings_are_okay (0.00s)
>     --- FAIL: TestMultilineString/Multiline_strings_are_not_allowed (0.00s)
>     	lexer_test.go:126: Test 'Multiline strings are not allowed' failed with wrong error: 'graphql: syntax error: literal not terminated. See near  (line 1, column 1)'. Error should be: 'graphql: syntax error: literal not terminated. See near "Hello (line 1, column 1)'

Thank you!

2020-10-07 19:42 UTC, suntoucha commented
Tests are OK now

The only difference I've noticed is that SemaphoreCI runs on go 1.11 by default

2020-11-12 19:29 UTC, pavelnikolov commented on internal/common/lexer.go
> +}
Add empty line at the end.

2020-11-12 19:30 UTC, pavelnikolov commented on internal/common/lexer_test.go
> +}
Add empty line at the end, please

2020-11-12 19:32 UTC, pavelnikolov commented on internal/common/lexer_test.go
> +
(nitpick) I'd remove this empty line

2020-11-12 19:33 UTC, pavelnikolov requested changes
Thank you. Can you, please fix the empty lines and I'd be happy to merge this PR.

2020-11-13 08:26 UTC, suntoucha commented on internal/common/lexer.go
> +}
Done

2020-11-13 08:26 UTC, suntoucha commented on internal/common/lexer_test.go
> +}
Done

2020-11-13 08:26 UTC, suntoucha commented on internal/common/lexer_test.go
> +
Done

2020-11-13 09:06 UTC, merged